version: '3.7'
services:
  caddy:
    image: registry.digitalocean.com/watheia/caddy-server:ci
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    restart: unless-stopped
    # labels:
    # - caddy.email: admin@watheia.org

  home:
    depends_on:
      - caddy
    build: "./apps/client/home"
    networks:
      - caddy
    ports:
      - 8080:80
      - 8443:443
    labels:
      caddy: www.watheia.org
      caddy.reverse_proxy: '{{upstreams 80}}'

networks:
  caddy:
    external: true

networks:
  caddy:
    external: true

volumes:
  caddy_data: {}

